### ISSUE TITLE
It does not changes info when server has been changed.

### ISSUE THREAD

**Issue by SJang1** [nomomo/Twitch-Server-Info#1]
When the twitch streaming server changes while watching live, this shows up not a current server, shows only the first server when connecting to steam.

Auto refreshing connected server info seems to be needed.

**Comment by nomomo** [comment]
The current code is not designed to show only the first connected server. If the server is changed while the user is watching the live video, the new server address will be displayed.

Currently this script shows a server where the user downloads a .ts file that is a live video segment. The Twitch video player downloads .ts files approximately every two seconds. This script checks the server address every time a player downloads a ts file. The script changes the server display if the current server is different from the previously displayed server.

If the server display does not change when the server changes, it is a bug. But I didn't find any problem in the code.

The user may not notice that the server display has already changed. I'll consider how to add the display of server change history as a user option.

**Comment by SJang1** [comment]
I have checked it works. thanks.
