### ISSUE TITLE
문자가 중첩되어 표시됩니다

### ISSUE THREAD

**Issue by Mishasama** [nomomo/Twitch-Server-Info#3]
![](https://user-images.githubusercontent.com/54498172/174477354-2ba1f7b2-ee37-40ad-a9dc-dc37aa106751.png)

시간이 지남에 따라 다른 서버를 계속 전환하면 이렇게 됩니다.

**Comment by nomomo** [comment]
확인 감사드립니다. 0.1.1 버전으로 스크립트를 업데이트 했습니다.
이번에 업데이트 한 0.1.1 버전은 기존 스크립트에서 몇 가지를 수정해서 개인적으로 사용해왔던 개발버전인데, 사용하는 동안 리포트 주신 문제가 발생하지 않았던 것이라 아마도 문제가 없을 것 같습니다.
혹시 문제가 재발생 되면 알려주세요~

**Comment by Mishasama** [comment]
고맙습니다. 문제가 해결되었습니다.
