### ISSUE TITLE
Looks like you need to update the server list again

### ISSUE THREAD

**Issue by thinkpad4** [nomomo/Twitch-Server-Info#5]
@nomomo Looks like you need to update the list, there are more servers now and they have changed names `https://twitchstatus.com/`

**Comment by nomomo** [comment]
Thank you for raising the issue. I have confirmed that "phx" has been removed from the server list of TwitchStatus, and "dfw56" and "mfe" have been added. For details, please refer to the xlsx file below.
[231126_comparison.xlsx](https://github.com/nomomo/Twitch-Server-Info/files/13465878/231126_comparison.xlsx)

I will update the script version to 0.1.3.

**Comment by nomomo** [comment]
Updated script version to 0.1.3.
